import styles from "./about.module.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "About Page",
  description: "Generated by create next app",
  authors: [{ name: "daniel Ouattara", url: "daniel.ouattara@gmx.com" }],
};

export default function AboutLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <nav>About navbar</nav>
      <main className={styles.main}>{children}</main>
    </>
  );
}
