import type { Metadata } from "next";
import { getAllUsers } from "@/libs";
import Link from "next/link";
import { Suspense } from "react";
import { UsersList } from "@/components";

export const metadata: Metadata = {
  title: "Users Page",
  description: "Generated by create next app",
  authors: [{ name: "daniel Ouattara", url: "daniel.ouattara@gmx.com" }],
};

export default async function UsersPage() {
  const usersData = getAllUsers();

  return (
    <>
      <h1>Users Page</h1>
      <Link href={"/"}>to Home</Link> | <Link href={"/about"}>to About</Link>
      <Suspense fallback={<h2>Loading users data...</h2>}>
        <UsersList promise={usersData} />
      </Suspense>
    </>
  );
}
