import type { Metadata } from "next";
import { getAllUsers } from "@/libs";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Users Page",
  description: "Generated by create next app",
  authors: [{ name: "daniel Ouattara", url: "daniel.ouattara@gmx.com" }],
};

export default async function UsersPage() {
  const users = await getAllUsers();

  return (
    <>
      <h1>Users Page</h1>
      <Link href={"/"}>to Home</Link> |<Link href={"/about"}>to About</Link>
      <ul>
        {users.map((user) => (
          <li key={user.id}>
            <Link href={`/users/${user.id}`}>{user.name}</Link>
          </li>
        ))}
      </ul>
    </>
  );
}
